# Generated by Django 5.2.4 on 2025-11-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='userid',
            field=models.CharField(default='tempuser', max_length=30, unique=True),
        ),
    ]
