# Generated by Django 5.2.4 on 2025-11-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default='TEMP_ID', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='userid',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
